name: sign_in_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^3.0.3
  battery_plus: ^3.0.1
  google_sign_in: ^5.0.7
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.0
  flutter_facebook_auth: ^3.5.2
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
